title: Sharkmu's Personal Website
description: A simple personal website powered by Github Pages
markdown: kramdown
theme: minima

collections:
  blog:
    output: true
    permalink: /v2/blog/:title/